### ISSUE TITLE
Add type and (file)name as private element to SCL

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-scl-data-service#12]
As enduser
I want the type and (file)name to be stored
So that later the SCL can be exported to a file system with that name

We decided to store the (file)name and type (extension) as private element in the SCL.
This way this information can be used to search for and also save the SCL again to the file system.

Acceptance criteria:
- Name and Type are added as private element when POST call is made (Create new SCL)
- Type is set/added when PUT call is made (Update SCL) and name is copied from previous version if not already in new SCL.
- For the ListResponse and VersionsResponse the Item class is extended with the name, this will be filled with the name from the private extension in CompasSclDataBaseXRepository (list and listVersionsByUUID methods).

**Comment by Sander3003** [comment]
Look it up in the 61850 documentation. Check with peers. https://lfenergy.slack.com/archives/C01926K9D39/p1620825917091100

**Comment by Sander3003** [comment]
Type could be an enum
