### ISSUE TITLE
Add SCL Type STD to List

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-scl-data-service#152]
As a Engineer 
I want to be able to select the SCL Type during opening and saving a SCL File
So that I can store and retrieve this type of SCL.

There is a enum SCLType containing all types of SCLs. We need to add the type STD ("System Template Definition") to this Enum.
Maybe also think about moving this Enum Class to the CoMPAS Core repository (Module "commons").

**Comment by Sander3003** [comment]
ASD stands for Application specification definition / https://www.pacw.org/basic-application-profiles
