### ISSUE TITLE
Add SCL name uniqueness check (BaseX)

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-scl-data-service#203]
As an Engineer
I want to be informed if my project name in CoMPAS already exists in the SCL file type
So I prevent confusion (projects with the same name)

When the users enter a name in this window:
![image](https://user-images.githubusercontent.com/7427358/162951723-7314931b-65cc-40c3-9ee3-776f7080e7c4.png)

and clicks on the "save" button, CoMPAS should check if the name already exists for the selected SCL type.
If the name matches an existing one an error should show.

Background:
In issue #197 the base is created to check the uniqueness for the PostgreSQL implementation. 
For BaseX this new method in the repository needs to be implemented to also check for uniqueness.
- Implement the method to retrieve all the latest versions and retrieve the SclName private from the SCL XML. (Private Element "SclName" under the private section (type: "compas_scl") under the SCL Tag.)
- Use these names to see if the (new) name is already used.

**Comment by Sander3003** [comment]
BaseX support is dropped
