### ISSUE TITLE
Add Rest API to check if a SCL Name isn't already used

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-scl-data-service#204]
As a engineer
I want to have faster feedback when changing/using a SCL Name
So that I can change the name before the add/save returned a error

Background:
Issues #197 and #203 implement check the SCL Name isn't already used during adding/saving of the SCL File.
It would be nice that the front-end can make a call to check this before executing the add/save action.
- Add a new Rest API Call (Post) to check if a name isn't already used ("/scl/v1/{type}/checkname")
- It will retrieve the filename are parameter in the Request Body
- Use this name to make the call the service layer, which make the call to the repository.
- In the response return true/false to indicate if the name is unique.

**Comment by JakobVogelsang** [comment]
@dlabordus is this issue still valid as it is formulated?

**Comment by Sander3003** [comment]
Yes, however it is a low priority issue in my opinion.

**Comment by Sander3003** [comment]
{TYPE}_read is fine for me, if the user has insufficient rights, it cannot save the changes to the database.
