### ISSUE TITLE
Show filename and substation name instead of ID 

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-scl-data-service#26]
As a user-interface user
I want to see the filename (private element) and optional (if the name is theire) substationname (SCL) for SCD and SCD
So I can easly find the correct SCL file without knowing the UUID

Background
To make the CoMPAS/OpenSCD easy to use; 
A private element needs to be added first.
Find the SCL substation field in IEC61850

Acceptance
Works with SCD/SSD/ICD/IID/CID/SED/ISD

**Comment by Sander3003** [comment]
@dlabordus is this already fixed?

**Comment by Flurb** [comment]
@Sander3003 For me, it's not clear what the outcome of this story should be.
We added the private elements SclFileType and SclFilename.
We also replaced the ID in OpenSCD with the previous SclFilename value when a SCL file is opened.

is this enough?

**Comment by Sander3003** [comment]
Lets discuss it during the refinement;

**Comment by Sander3003** [comment]
It is already done.
