### ISSUE TITLE
Publish Docker images with version / latest version

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-scl-data-service#32]
As a developer
I want to publish the latest version of the SCL dataservice
So I can test them using Docker hub

Acceptance criteria:
- Publish a release version when a release is created. Also mark that release as "latest"

Remark:
- Development versions aren't pushed to Docker Hub. These can be build and run locally.

Background:
Similar to the Docker Hub publishment of our OpenSCD repository.

**Comment by Sander3003** [comment]
@Flurb what is the status of the issue?

**Comment by Flurb** [comment]
@Sander3003 Still needs to be done.
