### ISSUE TITLE
Remove BaseX database support

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-scl-data-service#331]
Since BaseX has completely rewritten their API and it is not used a-lot , support will be dropped.

Todo:
Send out a slack message to inform that BaseX support will be dropped
Remove support in this repository (this is the most work)
Remove relevant tests
Remove form deployment + documentation
Check on internal deployments on the use of BaseX

Background: It is hard to split;

Approach for this repository: 
remove a basex-repository and fix the pointers in the code

**Comment by pascalwilbrink** [comment]
Fixed by #355
