### ISSUE TITLE
SCL Data Service should support DTO's

### ISSUE THREAD

**Issue by pascalwilbrink** [com-pas/compas-scl-data-service#357]
In order to make the implementation better to maintain; The idea is to replace existing custom code by standard implementation. In order to do so; the DTO is concept is needed to prevent errors.

If we want to migrate to native Repositories (like has been done in Sitipe), we need to support DTO's (Data Transfer Objects).

App > Service > Repository
DTO > DTO/Entity translation > Entity

The Input and Output of the Service package should be DTO's.
The translation from/to a DTO should be in the Service.

**Comment by Sander3003** [comment]
Can this be closed @pascalwilbrink ?

**Comment by Sander3003** [comment]
Considered closed
