### ISSUE TITLE
Error Handling in Rest Service

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-scl-data-service#8]
As a user of the Rest Service 
I would like to have nicer Error Responses
So that we can handle the different kind of situations better.

Add Error Handling to the project, so the standard HTML Page isn't displayed, but nicer responses, maybe some kind of XML Error Response.

Use standard http status codes:
Find: 404 if not found
Input error: 400 + body
Other errors: 500 + body

Background:
This might be possible using Quarkus

**Comment by Sander3003** [comment]
Find: 404 if not found
Input error: 400 + body
Other errors: 500 + body

**Comment by Sander3003** [comment]
Might be possible with Quarkus

**Comment by dlabordus** [comment]
Some standard handling is already build in during the issue of validating the Request Body.
But there are still situations that HTML is displayed or for instance a 404 with BaseX needs to be designed.
